# Input entities
settings:
  # Power settings
  power_limit: input_number.ev_load_balancing_power_limit
  power_limit_extended: input_number.ev_load_balancer_extended_power_limit
  charge_mode: input_select.ev_charge_mode
  soc_threshold: input_number.ev_soc_threshold

# Charger settings
charger:
  # Sensor references
  home_power: sensor.netto_verbruik_huis_lp
  connection_state: sensor.alfen_eve_connection_state
  mode3_state: sensor.alfen_mode3_state_socket_1
  active_power: sensor.alfen_eve_active_power_total_socket_1
  current: number.alfen_eve_power_connector_max_current_socket_1
  phase_select: select.alfen_eve_installation_max_allowed_phases
  max_phases: 3
  max_current: 16
  min_current: 6
  nominal_voltage: 230

# Car settings
defaults:
  # Charging parameters
  max_current: 16
  min_current: 6
  
  # Battery settings
  battery_capacity_wh: 80000
  soc_threshold: 0
  
  # Time settings
  time_sensor: "07:00"

cars:
  bmw_ix3:
    # Required parameters
    soc_sensor: sensor.ix3_m_sport_remaining_battery_percent
    time_sensor: input_datetime.ev_charge_time_target
    battery_capacity_wh: 80000